spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kyc_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379

server:
  port: 8080
jwt:
  secret: aaaaabbbbb1111122222333334444455
  expiration: 86400000