# Application Info
spring.application.name=kyc_live_interview_api

# REST API Port
server.port=8080

# PostgreSQL DB (Docker service name will be 'db')
spring.datasource.url=jdbc:postgresql://kyc-db:5432/kyc_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
SPRING_DATASOURCE_URL=jdbc:postgresql://kyc-db:5432/kyc_db?prepareThreshold=0


# Hibernate Settings

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Istanbul

# Parametre binding (Hibernate 6)
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# JWT Secret
jwt.secret=aaaaabbbbb1111122222333334444455

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# Socket.IO Config (used by SocketIOServer)
socket.port=8000
socket.host=0.0.0.0

app.disconnect-timeout-seconds=60
